### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by sayhelloto1988** [uhiu/StyLess#5]
I have run your code, but the experimental results are quite different from those in your paper. In particular, the results using RN50 on MTDSI are 20% lower than those in your paper. I want to ask if I haven't set it up properly?

**Comment by uhiu** [comment]
Hi, I have followed the instructions in README.md to rerun the MTDSI based on RN50 and obtained a similar result to the original paper. I am not sure if you have modified the code, but I think the code is correct.

By the way, I would like to mention that the current code version only supports `batch size = 1`. Modifying the batch size will yield wrong results. I will update the code in the future to include a mini-batch version.
